version: "3.9" # optional since  v1 .27. 0
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/
    depends_on:
      - mysqldb
  
  mysqldb:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dockerwebexport

  myadmin:
    image: "phpmyadmin/phpmyadmin"
    environment:
      PMA_HOST: mysqldb
      PMA_USER: root
      PMA_PASSWORD: dockerwebexport
    ports:
      - 8081:80
    depends_on:
      - mysqldb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
    depends_on:
      - mysqldb